let str1 = "Hello";
let str2 = "World";
let result = str1 + str2; // " HelloWorld"
str1 = "Hello"
str2 = "World"
result = str1 + str2  # "HelloWorld"
String str1 = "Hello";
String str2 = "World";
String result = str1 + str2; // "HelloWorld"
std::string str1 = "Hello";
std::string str2 = "World";
std::string result = str1 + str2; // "HelloWorld"
string str1 = "Hello";
string str2 = "World";
string result = str1 + str2; // "HelloWorld"
str1 = "Hello"
str2 = "World"
result = str1 + str2  # "HelloWorld"
let str1 = "Hello"
let str2 = "World"
let result = str1 + str2  // "HelloWorld"
$str1 = "Hello";
$str2 = "World";
$result = $str1 . $str2; // "HelloWorld"
SELECT CONCAT('Hello', 'World') AS result; // "HelloWorld"
