let str1: string = "Hello, ";
let str2: string = "world!";
let result = str1 + str2;  // "Hello, world!"
let str1: string = "Hello, ";
let str2: string = "world!";
let result = `${str1}${str2}`;  // "Hello, world!"
let str1: string = "Hello, ";
let str2: string = "world!";
let result = str1.concat(str2);  // "Hello, world!"
