name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - run: git fetch
    - run: git pull
    - name: Build
      run: |
        npm install
        grunt
    - run: git config --global user.name "${{ secrets.NAME }}"
    - run: git config --global user.email "${{ secrets.EMAIL }}"
    - name: NODE RUN
      run: node index
    - name: GIT PUSH
      run: git push
      env:
        API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}
